import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import turtle from "../styles/turtle.jpg"

const body = `Sosteniamo il centro e chiediamo che venga ritirata l'ordinanza n°4 del 03/09/2021 del Comune di Lampedusa che prevede la chiusura immediata delle attività del centro.`
const to =['segreteria.presidente@regione.sicilia.it','segreteria.ministro@minambiente.it','totomartellosindacolampedusa@gmail.com'] 
//(#f57a32)

const cc = 'lampedusaturtlerescue@gmail.com'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lampedusa Turtle Rescue</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bgWrap}>
        <Image
          alt="Turtle"
          src={turtle}
          layout="fill"
          objectFit="cover"
          quality={100}
          placeholder="blur"
        />
      </div>
    
      <h1 className=" fixed top-0 text-white text-3xl m-4 text-center">
          Lampedusa Turtle Rescue
        </h1>
    
    
      <main className="fixed bottom-0 pb-4 pt-20	 text-center w-full" style={{'background':'linear-gradient(rgba(46,151,154,0), rgba(46,151,154,0.3), rgb(14 45 46))'}}>
     
        <h1 className="text-white text-3xl m-4">
          Firma le nostre petizioni per evitare la chiusura del centro
        </h1>

        <button onClick={() => window.open(
          `https://chng.it/4JNTSmBH`,
          '_blank' // <- This is what makes it open in a new window.
        )}
          className="m-2 bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded">
          Change.org
        </button>

<p className="text-white text-2xl m-1">e invia</p>
        <button onClick={() => window.open(
          `mailto:${to.join(',')}?cc=${cc}&body=${body}&subject=Sostegno al Lampedusa Turtle Rescue`,
          '_blank' // <- This is what makes it open in a new window.
        )}
          className="m-2 bg-yellow-500 hover:bg-yellow-600 text-white font-bold py-2 px-4 rounded">
          Email precompilata
        </button>


      </main>


    </div>
  )
}
